[tox]
isolated_build = True
envlist = lint, py38, py39, py310, py311, py312
skip_missing_interpreters = true

[common]
sources = src/dhcp_notify test

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312, lint

[testenv]
extras = test
commands = pytest --basetemp="{envtmpdir}" {posargs}

[testenv:lint]
commands =
    flake8 {[common]sources}
    black --check --verbose --diff {[common]sources}
    isort --check-only --diff {[common]sources}
    rstcheck -r .

[flake8]
max-line-length = 88

[pytest]
addopts =
    --cov=dhcp_notify
    --cov=test
    --cov-report=term-missing
    --cov-fail-under=100
    --cov-branch
    --no-cov-on-fail
