# Example configuration for dhcp-notify.
#
# Commented settings are optional (with default values as shown here).
# Edit this file and save it at '/etc/dhcp_notify.toml'.

# A list of MAC addresses to ignore
#ignore_macs = []

# A list of DHCP actions to ignore
#ignore_actions = []

# The SMTP host port and TLS config
[smtp]
host = "smtp.example.com"
#port = "465"
#tls = "tls"

# smtp credentials (optional, omit for anonymous SMTP)
[smtp.credentials]
username = "user@example.com"
password = "secret"

# email message config
[message]
from_addr = "DHCP Notifications <dhcp-notify@example.com>"
to_addr = "DHCP Notifications <dhcp-notify@example.com>"
#subject = "[dhcp-notify] DHCP Lease Notification"
