#!/bin/sh

set -eu

SCRIPT_NAME="${0##*/}"
CONFIGFILE='/etc/dhcp_notify'

# Default values for optional configs
DEFAULT_EMAIL_SUBJECT='[dhcp-notify] DHCP Lease Notification'
DEFAULT_MAILGUN_API_URL='https://api.mailgun.net/v3'

load_config() {
    errors=0
    optional_configs='MAILGUN_API_URL EMAIL_SUBJECT'
    required_configs='MAILGUN_API_SECRET EMAIL_DOMAIN EMAIL_FROM EMAIL_TO'

    . "${CONFIGFILE}"

    # Supply default values for optional configs
    for varname in ${optional_configs}; do
        eval : "\${${varname}:=\${DEFAULT_${varname}}}"
    done

    # Print error  messages for missing required configs
    for varname in ${required_configs}; do
        if eval [ -n "\${${varname}:-}" ]; then
            printf '%s: Error: %s is not set.\n' "${SCRIPT_NAME}" "${varname}" >&2
            errors=$((errors+1))
        fi
    done

    if [ ${errors} -gt 0 ]; then
        printf '%s: Failed to load config from "%s"\n' "${SCRIPT_NAME}" "${CONFIGFILE}"
        return 1
    fi
}


send_email() {
    message="$1"
    credentials="api:${MAILGUN_API_KEY}"
    email_send_url="${MAILGUN_API_URL%/}/${EMAIL_DOMAIN}/messages"

    curl --fail --show-error --silent --user "${credentials}" --form "from=${EMAIL_FROM}" \
        --form "to=${EMAIL_TO}" --form "subject=${EMAIL_SUBJECT}" --form "text=${message}" \
        "${email_send_url}" > /dev/null
}


main() {
    message="$*"

    load_config
    send_email "${message}"
}


main "$@"
