#!/bin/sh

set -eu

SCRIPT_NAME="${0##*/}"
CONFIGFILE='/etc/dhcp_notify'

# Default values for optional configs
DEFAULT_EMAIL_SUBJECT='[dhcp-notify] DHCP Lease Notification'
DEFAULT_MAILGUN_API_URL='https://api.mailgun.net/v3'

load_config() {
    optional_configs='MAILGUN_API_URL EMAIL_SUBJECT'
    required_configs='MAILGUN_API_KEY EMAIL_DOMAIN EMAIL_FROM EMAIL_TO'
    missing_configs=''

    . "${CONFIGFILE}"

    # Supply default values for optional configs
    for varname in ${optional_configs}; do
        eval : "\${${varname}:=\${DEFAULT_${varname}}}"
    done

    # Print error  messages for missing required configs
    for varname in ${required_configs}; do
        if eval [ -z \"\${${varname}:-}\" ]; then
            sep="${missing_configs:+, }"
            missing_configs="${missing_configs}${sep}${varname}"
        fi
    done

    if [ -n "${missing_configs}" ]; then
        printf '%s: Required configs not set in "%s": %s\n' \
            "${SCRIPT_NAME}" "${CONFIGFILE}" "${missing_configs}" >&2
        return 1
    fi
}


send_email() {
    message="$1"
    credentials="api:${MAILGUN_API_KEY}"
    email_send_url="${MAILGUN_API_URL%/}/${EMAIL_DOMAIN}/messages"

    if [ -z "${message}" ]; then
        printf '%s: No message to send\n' "${SCRIPT_NAME}" >&2
        return 1
    fi

    curl --fail --show-error --silent --user "${credentials}" --form "from=${EMAIL_FROM}" \
        --form "to=${EMAIL_TO}" --form "subject=${EMAIL_SUBJECT}" --form "text=${message}" \
        "${email_send_url}" > /dev/null
}


main() {
    message="$*"

    load_config
    send_email "${message}"
}


main "$@"
